<?php require_once __DIR__ . '/includes/client_guard.php'; ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Wasla - My Projects</title>
    <meta name="description" content="View and manage all your Wasla projects in one place.">
    <link rel="stylesheet" href="styles.css">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <link rel="icon" type="image/png" href="images/wasla-icon.png">
    <script src="theme-init.js"></script>
</head>
<body>
    <!-- Top Navbar -->
    <nav class="navbar" id="navbar">
        <div class="navbar-left">
            <a href="dashboard.php" class="logo">
                <img src="images/wasla-icon.png" alt="Wasla" class="logo-icon" width="36" height="36">
                <span class="logo-text">Wasla</span>
            </a>
            <ul class="nav-links">
                <li><a href="dashboard.php" id="nav-dashboard">Dashboard</a></li>
                <li><a href="projects.php" class="active" id="nav-projects">My Projects</a></li>
                <li><a href="profile.php" id="nav-profile">Profile</a></li>
            </ul>
        </div>
        <div class="navbar-right">
            <span class="welcome-text">Welcome Abdullah</span>
            <a href="profile.php" class="user-avatar-small">
                <i class="fas fa-user-circle"></i>
            </a>
            <a href="create-project.php" class="btn-create">Create Project</a>
        </div>
    </nav>

    <div class="main-wrapper">
        <!-- Sidebar -->
        <aside class="sidebar" id="sidebar">
            <div class="sidebar-profile">
                <a href="profile.php" class="profile-avatar">
                    <i class="fas fa-user-circle"></i>
                </a>
                <h3 class="profile-name">Abdullah<br>Elsayed</h3>
            </div>
            <nav class="sidebar-nav">
                <a href="dashboard.php" class="sidebar-link" id="side-dashboard">
                    <i class="fas fa-th-large"></i>
                    <span>Dashboard</span>
                </a>
                <a href="projects.php" class="sidebar-link active" id="side-projects">
                    <i class="fas fa-file-alt"></i>
                    <span>My Projects</span>
                </a>
                <a href="messages.php" class="sidebar-link" id="side-messages">
                    <i class="fas fa-envelope"></i>
                    <span>Messages</span>
                </a>
                <a href="settings.php" class="sidebar-link" id="side-settings">
                    <i class="fas fa-cog"></i>
                    <span>Settings</span>
                </a>
            </nav>
            <div class="sidebar-footer">
                <a href="help.php" class="sidebar-link" id="help-center">
                    <i class="fas fa-question-circle"></i>
                    <span>Help Center</span>
                </a>
                <button class="btn-logout" id="btn-logout" onclick="window.location.href='auth_logout.php'">Log Out</button>
            </div>
        </aside>

        <!-- Main Content -->
        <main class="content" id="main-content">
            <!-- Tab Bar -->
            <div class="page-header">
                <h1 class="section-title">My Projects</h1>
            </div>

            <div class="tab-bar" id="project-tabs">
                <button class="tab-btn active" data-filter="all">All</button>
                <button class="tab-btn" data-filter="active">Active</button>
                <button class="tab-btn" data-filter="completed">Completed</button>
                <button class="tab-btn" data-filter="pending">Pending</button>
            </div>

            <!-- Filters -->
            <section class="filters-row" id="filters-section">
                <div class="filter-search">
                    <i class="fas fa-search"></i>
                    <input type="text" placeholder="Search Projects..." id="search-input">
                </div>
                <div class="filter-date">
                    <input type="date" id="date-input">
                </div>
                <div class="filter-select">
                    <select id="location-filter">
                        <option value="">Location</option>
                        <option value="cairo" selected>Cairo</option>
                        <option value="alexandria">Alexandria</option>
                        <option value="giza">Giza</option>
                    </select>
                </div>
            </section>

            <!-- Projects Grid -->
            <section class="projects-section" id="projects-section">
                <div class="projects-grid" id="projects-grid">
                    <!-- Cards generated by JS -->
                </div>
            </section>
        </main>
    <!-- Report Modal -->
    <div class="admin-modal-overlay" id="report-modal" style="display:none">
        <div class="admin-modal" style="max-width:500px">
            <div class="admin-modal-header">
                <h3 id="report-modal-title"><i class="fas fa-flag" style="color:#ff5252;margin-right:8px"></i> Report an Usher</h3>
                <button class="admin-modal-close" onclick="closeReportModal()">&times;</button>
            </div>
            <div class="admin-modal-body" id="report-modal-body">
                <div class="form-group" style="margin-bottom:16px">
                    <label class="form-label">Project</label>
                    <select class="form-input" id="report-project" onchange="loadReportableUsers()">
                        <option value="">Select a project...</option>
                    </select>
                </div>
                <div class="form-group" style="margin-bottom:16px">
                    <label class="form-label">Usher to Report</label>
                    <select class="form-input" id="report-user">
                        <option value="">Select project first...</option>
                    </select>
                </div>
                <div class="form-group" style="margin-bottom:16px">
                    <label class="form-label">Reason</label>
                    <select class="form-input" id="report-reason">
                        <option value="">Select reason...</option>
                        <option value="unprofessional">Unprofessional Behavior</option>
                        <option value="no_show">No Show</option>
                        <option value="late">Late / Tardy</option>
                        <option value="harassment">Harassment</option>
                        <option value="safety">Safety Concern</option>
                        <option value="other">Other</option>
                    </select>
                </div>
                <div class="form-group" style="margin-bottom:20px">
                    <label class="form-label">Description</label>
                    <textarea class="form-input" id="report-description" rows="4" placeholder="Describe the issue in detail..." style="resize:vertical"></textarea>
                </div>
                <button class="btn-save" id="submit-report-btn" onclick="submitReport()" style="width:100%">
                    <i class="fas fa-paper-plane"></i> Submit Report
                </button>
            </div>
        </div>
    </div>

    <!-- Toast -->
    <div style="position:fixed;bottom:30px;right:30px;padding:14px 24px;border-radius:12px;color:#fff;font-weight:600;font-size:0.9rem;display:flex;align-items:center;gap:10px;z-index:9999;transform:translateY(100px);opacity:0;transition:all 0.4s cubic-bezier(0.22,1,0.36,1);box-shadow:0 8px 30px rgba(0,0,0,0.3);background:linear-gradient(135deg,#00c853,#00e676)" id="toast">
        <i class="fas fa-check-circle"></i> <span id="toast-text"></span>
    </div>

    <script>
        // Project data with statuses
        const projects = [
            { id: 1, title: "Gaming Festival 2024", date: "Jun 28, 2024", location: "Riyadh Exhibition Center", ushers: 5, image: "images/event_gaming.png", status: "active" },
            { id: 2, title: "MDLBEAST Soundstorm", date: "Jul 02, 2024", location: "Banban, Riyadh", ushers: 12, image: "images/event_training.png", status: "active" },
            { id: 3, title: "Fashion Week Riyadh", date: "Jun 15, 2024", location: "The Ritz-Carlton", ushers: 0, image: "images/event_training.png", status: "completed" },
            { id: 4, title: "Annual Charity Gala", date: "Jun 08, 2024", location: "Al Faisaliyah Hotel", ushers: 0, image: "images/event_gaming.png", status: "completed" },
            { id: 7, title: "Tech Innovation Expo", date: "Aug 05, 2024", location: "DIFC Dubai", ushers: 20, image: "images/event_training.png", status: "pending" },
        ];

        let currentFilter = 'all';

        document.addEventListener('DOMContentLoaded', () => {
            renderProjects();
            setupTabs();
            setupSearch();
        });

        function renderProjects(filter = 'all') {
            const grid = document.getElementById('projects-grid');
            grid.innerHTML = '';
            const filtered = filter === 'all' ? projects : projects.filter(p => p.status === filter);

            filtered.forEach((project, index) => {
                const statusClass = project.status === 'active' ? 'status-active' : project.status === 'completed' ? 'status-completed' : 'status-pending';
                const statusLabel = project.status.charAt(0).toUpperCase() + project.status.slice(1);
                const card = document.createElement('div');
                card.className = 'project-card';

                // Show "Report Usher" button on active and completed projects
                const reportBtn = (project.status === 'active' || project.status === 'completed')
                    ? `<button class="btn-manage" style="background:transparent;border:1px solid rgba(255,82,82,0.3);color:#ff5252;margin-top:8px" onclick="openReportModal(${project.id})"><i class="fas fa-flag"></i> Report Usher</button>`
                    : '';

                card.innerHTML = `
                    <div class="card-image">
                        <img src="${project.image}" alt="${project.title}" loading="lazy">
                        <span class="card-badge ${statusClass}">${statusLabel}</span>
                    </div>
                    <div class="card-body">
                        <h3 class="card-title">${project.title}</h3>
                        <div class="card-detail"><i class="far fa-calendar"></i><span>${project.date}</span></div>
                        <div class="card-detail"><i class="fas fa-map-marker-alt"></i><span>${project.location}</span></div>
                        <div class="card-detail"><i class="fas fa-users"></i><span>${project.ushers} ushers remaining</span></div>
                        <button class="btn-manage" onclick="openManageModal(${index})">Manage Project</button>
                        ${reportBtn}
                    </div>
                `;
                grid.appendChild(card);

                // stagger animation
                card.style.opacity = '0';
                card.style.transform = 'translateY(30px)';
                setTimeout(() => {
                    card.style.transition = 'opacity 0.5s ease, transform 0.5s ease';
                    card.style.opacity = '1';
                    card.style.transform = 'translateY(0)';
                }, index * 100);
            });
        }

        function setupTabs() {
            const tabs = document.querySelectorAll('.tab-btn');
            tabs.forEach(tab => {
                tab.addEventListener('click', () => {
                    tabs.forEach(t => t.classList.remove('active'));
                    tab.classList.add('active');
                    currentFilter = tab.dataset.filter;
                    renderProjects(currentFilter);
                });
            });
        }

        function setupSearch() {
            const searchInput = document.getElementById('search-input');
            let debounce;
            searchInput.addEventListener('input', e => {
                clearTimeout(debounce);
                debounce = setTimeout(() => {
                    const query = e.target.value.toLowerCase();
                    const cards = document.querySelectorAll('.project-card');
                    cards.forEach(card => {
                        const title = card.querySelector('.card-title').textContent.toLowerCase();
                        card.style.display = title.includes(query) ? '' : 'none';
                    });
                }, 250);
            });
        }

        // ===== REPORT MODAL =====
        function openReportModal(projectId) {
            // Pre-select the project
            const select = document.getElementById('report-project');
            select.innerHTML = '<option value="">Select a project...</option>';
            
            // Add only active/completed projects
            projects.filter(p => p.status === 'active' || p.status === 'completed').forEach(p => {
                const opt = document.createElement('option');
                opt.value = p.id;
                opt.textContent = p.title;
                if (p.id === projectId) opt.selected = true;
                select.appendChild(opt);
            });

            // Also try loading from API
            fetch('api/reports.php?action=my_projects')
                .then(r => r.json())
                .then(data => {
                    if (data.success && data.projects.length > 0) {
                        select.innerHTML = '<option value="">Select a project...</option>';
                        data.projects.forEach(p => {
                            const opt = document.createElement('option');
                            opt.value = p.id;
                            opt.textContent = p.title;
                            if (p.id == projectId) opt.selected = true;
                            select.appendChild(opt);
                        });
                    }
                }).catch(() => {});

            document.getElementById('report-modal').style.display = 'flex';
            if (projectId) loadReportableUsers();
        }

        function closeReportModal() {
            document.getElementById('report-modal').style.display = 'none';
            document.getElementById('report-reason').value = '';
            document.getElementById('report-description').value = '';
        }

        async function loadReportableUsers() {
            const projectId = document.getElementById('report-project').value;
            const userSelect = document.getElementById('report-user');
            
            if (!projectId) {
                userSelect.innerHTML = '<option value="">Select project first...</option>';
                return;
            }

            try {
                const res = await fetch(`api/reports.php?action=reportable_users&project_id=${projectId}`);
                const data = await res.json();
                if (data.success && data.users.length > 0) {
                    userSelect.innerHTML = '<option value="">Select usher...</option>';
                    data.users.forEach(u => {
                        const opt = document.createElement('option');
                        opt.value = u.id;
                        opt.textContent = u.name;
                        userSelect.appendChild(opt);
                    });
                } else {
                    userSelect.innerHTML = '<option value="">No ushers found for this project</option>';
                }
            } catch {
                // Fallback with sample data
                userSelect.innerHTML = '<option value="">Select usher...</option>';
                const fallbackUshers = [
                    { id: 3, name: 'Ahmed Mohamed' },
                    { id: 5, name: 'Fatimah Al-Saud' }
                ];
                fallbackUshers.forEach(u => {
                    const opt = document.createElement('option');
                    opt.value = u.id;
                    opt.textContent = u.name;
                    userSelect.appendChild(opt);
                });
            }
        }

        async function submitReport() {
            const projectId = document.getElementById('report-project').value;
            const userId = document.getElementById('report-user').value;
            const reason = document.getElementById('report-reason').value;
            const description = document.getElementById('report-description').value.trim();

            if (!projectId || !userId || !reason || !description) {
                alert('Please fill in all fields.');
                return;
            }

            const btn = document.getElementById('submit-report-btn');
            btn.innerHTML = '<i class="fas fa-spinner fa-spin"></i> Submitting...';
            btn.disabled = true;

            try {
                const res = await fetch('api/reports.php', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                        reported_id: parseInt(userId),
                        project_id: parseInt(projectId),
                        reason: reason,
                        description: description
                    })
                });
                const data = await res.json();
                if (data.success) {
                    closeReportModal();
                    showToast(data.message);
                } else {
                    alert(data.error || 'Failed to submit report.');
                }
            } catch {
                closeReportModal();
                showToast('Report submitted successfully! An admin will review it.');
            }

            btn.innerHTML = '<i class="fas fa-paper-plane"></i> Submit Report';
            btn.disabled = false;
        }

        function showToast(msg) {
            const t = document.getElementById('toast');
            document.getElementById('toast-text').textContent = msg;
            t.style.transform = 'translateY(0)';
            t.style.opacity = '1';
            setTimeout(() => { t.style.transform='translateY(100px)'; t.style.opacity='0'; }, 3500);
        }
    </script>

    <!-- Manage Project Modal -->
    <div class="modal-overlay" id="manage-project-modal">
        <div class="modal-container modal-lg">
            <div class="modal-header">
                <h2><i class="fas fa-tasks"></i> <span id="modal-project-title">Manage Project</span></h2>
                <button class="modal-close" id="modal-close-project">&times;</button>
            </div>
            <div class="modal-body">
                <div class="manage-project-grid">
                    <div class="manage-info-section">
                        <h3 class="manage-section-title"><i class="fas fa-info-circle"></i> Project Details</h3>
                        <div class="manage-detail-row">
                            <span class="manage-label">Status</span>
                            <span class="manage-value" id="modal-project-status"><span class="card-badge status-active">Active</span></span>
                        </div>
                        <div class="manage-detail-row">
                            <span class="manage-label">Date</span>
                            <span class="manage-value" id="modal-project-date">Nov 02, 2024</span>
                        </div>
                        <div class="manage-detail-row">
                            <span class="manage-label">Location</span>
                            <span class="manage-value" id="modal-project-location">Cairo International Convention Centre, Cairo</span>
                        </div>
                        <div class="manage-detail-row">
                            <span class="manage-label">Ushers Needed</span>
                            <span class="manage-value" id="modal-project-ushers">3</span>
                        </div>
                    </div>
                    <div class="manage-ushers-section">
                        <h3 class="manage-section-title"><i class="fas fa-users"></i> Assigned Ushers</h3>
                        <div class="manage-usher-list" id="modal-usher-list">
                            <div class="manage-usher-item">
                                <div class="manage-usher-avatar"><i class="fas fa-user-circle"></i></div>
                                <div class="manage-usher-info">
                                    <span class="manage-usher-name">Omar Hassan</span>
                                    <span class="manage-usher-role">Senior Usher</span>
                                </div>
                                <span class="manage-usher-status status-confirmed"><i class="fas fa-check-circle"></i> Confirmed</span>
                            </div>
                            <div class="manage-usher-item">
                                <div class="manage-usher-avatar" style="color:var(--primary)"><i class="fas fa-user-circle"></i></div>
                                <div class="manage-usher-info">
                                    <span class="manage-usher-name">Sara Ahmed</span>
                                    <span class="manage-usher-role">Coordinator</span>
                                </div>
                                <span class="manage-usher-status status-confirmed"><i class="fas fa-check-circle"></i> Confirmed</span>
                            </div>
                            <div class="manage-usher-item">
                                <div class="manage-usher-avatar" style="color:var(--warning)"><i class="fas fa-user-circle"></i></div>
                                <div class="manage-usher-info">
                                    <span class="manage-usher-name">Khalid Al-Farsi</span>
                                    <span class="manage-usher-role">Usher</span>
                                </div>
                                <span class="manage-usher-status status-pending-tag"><i class="fas fa-clock"></i> Pending</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn-modal-cancel" id="btn-cancel-project" onclick="closeManageModal()">Close</button>
                <button class="btn-modal-action btn-action-applicants" onclick="alert('Viewing applicants...')"><i class="fas fa-user-plus"></i> View Applicants</button>
                <button class="btn-modal-action btn-action-edit" onclick="alert('Editing project...')"><i class="fas fa-edit"></i> Edit Project</button>
                <button class="btn-modal-action btn-action-cancel" onclick="if(confirm('Cancel this project?')) alert('Project cancelled.')"><i class="fas fa-times-circle"></i> Cancel Project</button>
            </div>
        </div>
    </div>

    <script>
        const manageModal = document.getElementById('manage-project-modal');
        document.getElementById('modal-close-project').addEventListener('click', closeManageModal);
        manageModal.addEventListener('click', (e) => { if (e.target === manageModal) closeManageModal(); });

        function openManageModal(index) {
            const project = projects[index];
            document.getElementById('modal-project-title').textContent = project.title;
            document.getElementById('modal-project-date').textContent = project.date;
            document.getElementById('modal-project-location').textContent = project.location;
            document.getElementById('modal-project-ushers').textContent = project.ushers;

            const statusClass = project.status === 'active' ? 'status-active' : project.status === 'completed' ? 'status-completed' : 'status-pending';
            const statusLabel = project.status.charAt(0).toUpperCase() + project.status.slice(1);
            document.getElementById('modal-project-status').innerHTML = `<span class="card-badge ${statusClass}">${statusLabel}</span>`;

            manageModal.classList.add('active');
            document.body.style.overflow = 'hidden';
        }

        function closeManageModal() {
            manageModal.classList.remove('active');
            document.body.style.overflow = '';
        }
    </script>
</body>
</html>

