<?php require_once __DIR__ . '/includes/client_guard.php'; ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Wasla - My Projects</title>
    <meta name="description" content="View and manage all your Wasla projects in one place.">
    <link rel="stylesheet" href="styles.css?v=<?= time() ?>">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <link rel="icon" type="image/png" href="images/wasla-icon.png">
    <script src="wasla-theme.js"></script>
</head>
<body>
    <?php $active_page = 'projects'; ?>
    <?php include __DIR__ . '/includes/navbar.php'; ?>

    <div class="main-wrapper">
        <?php include __DIR__ . '/includes/sidebar.php'; ?>

        <!-- Main Content -->
        <main class="content" id="main-content">
            <!-- Tab Bar -->
            <div class="page-header">
                <h1 class="section-title">My Projects</h1>
            </div>

            <div class="tab-bar" id="project-tabs">
                <button class="tab-btn active" data-filter="all">All</button>
                <button class="tab-btn" data-filter="active">Active</button>
                <button class="tab-btn" data-filter="completed">Completed</button>
                <button class="tab-btn" data-filter="pending">Pending</button>
            </div>

            <!-- Filters -->
            <section class="filters-row" id="filters-section">
                <div class="filter-search">
                    <i class="fas fa-search"></i>
                    <input type="text" placeholder="Search Projects..." id="search-input">
                </div>
                <div class="filter-date">
                    <input type="date" id="date-input">
                </div>
                <div class="filter-select">
                    <select id="location-filter">
                        <option value="">Location</option>
                        <option value="Cairo">Cairo</option>
                        <option value="Sharm Elsheikh">Sharm Elsheikh</option>
                        <option value="North Coast">North Coast</option>
                        <option value="Riyadh">Riyadh</option>
                        <option value="Jeddah">Jeddah</option>
                        <option value="Dubai">Dubai</option>
                    </select>
                </div>
            </section>

            <!-- Projects Grid -->
            <section class="projects-section" id="projects-section">
                <div class="projects-grid" id="projects-grid">
                    <!-- Cards generated by JS -->
                </div>
            </section>
        </main>
    <!-- Report Modal -->
    <div class="admin-modal-overlay" id="report-modal" style="display:none">
        <div class="admin-modal" style="max-width:500px">
            <div class="admin-modal-header">
                <h3 id="report-modal-title"><i class="fas fa-flag" style="color:#ff5252;margin-right:8px"></i> Report an Usher</h3>
                <button class="admin-modal-close" onclick="closeReportModal()">&times;</button>
            </div>
            <div class="admin-modal-body" id="report-modal-body">
                <div class="form-group" style="margin-bottom:16px">
                    <label class="form-label">Project</label>
                    <select class="form-input" id="report-project" onchange="loadReportableUsers()">
                        <option value="">Select a project...</option>
                    </select>
                </div>
                <div class="form-group" style="margin-bottom:16px">
                    <label class="form-label">Usher to Report</label>
                    <select class="form-input" id="report-user">
                        <option value="">Select project first...</option>
                    </select>
                </div>
                <div class="form-group" style="margin-bottom:16px">
                    <label class="form-label">Reason</label>
                    <select class="form-input" id="report-reason">
                        <option value="">Select reason...</option>
                        <option value="unprofessional">Unprofessional Behavior</option>
                        <option value="no_show">No Show</option>
                        <option value="late">Late / Tardy</option>
                        <option value="harassment">Harassment</option>
                        <option value="safety">Safety Concern</option>
                        <option value="other">Other</option>
                    </select>
                </div>
                <div class="form-group" style="margin-bottom:20px">
                    <label class="form-label">Description</label>
                    <textarea class="form-input" id="report-description" rows="4" placeholder="Describe the issue in detail..." style="resize:vertical"></textarea>
                </div>
                <button class="btn-save" id="submit-report-btn" onclick="submitReport()" style="width:100%">
                    <i class="fas fa-paper-plane"></i> Submit Report
                </button>
            </div>
        </div>
    </div>

    <!-- Toast -->
    <div style="position:fixed;bottom:30px;right:30px;padding:14px 24px;border-radius:12px;color:#fff;font-weight:600;font-size:0.9rem;display:flex;align-items:center;gap:10px;z-index:9999;transform:translateY(100px);opacity:0;transition:all 0.4s cubic-bezier(0.22,1,0.36,1);box-shadow:0 8px 30px rgba(0,0,0,0.3);background:linear-gradient(135deg,#00c853,#00e676)" id="toast">
        <i class="fas fa-check-circle"></i> <span id="toast-text"></span>
    </div>

    <!-- Review Usher Modal -->
    <div class="admin-modal-overlay" id="review-modal" style="display:none">
        <div class="admin-modal" style="max-width:480px">
            <div class="admin-modal-header">
                <h3><i class="fas fa-star" style="color:#ffc107;margin-right:8px"></i> Review Usher</h3>
                <button class="admin-modal-close" onclick="closeReviewModal()">&times;</button>
            </div>
            <div class="admin-modal-body">
                <div class="form-group" style="margin-bottom:16px">
                    <label class="form-label">Usher</label>
                    <select class="form-input" id="review-usher">
                        <option value="">Loading ushers...</option>
                    </select>
                </div>
                <div class="form-group" style="margin-bottom:16px">
                    <label class="form-label">Rating</label>
                    <div id="star-rating" style="display:flex;gap:8px;font-size:1.8rem;cursor:pointer;">
                        <i class="far fa-star" data-rating="1" onclick="setRating(1)" style="color:#ffc107;transition:0.2s"></i>
                        <i class="far fa-star" data-rating="2" onclick="setRating(2)" style="color:#ffc107;transition:0.2s"></i>
                        <i class="far fa-star" data-rating="3" onclick="setRating(3)" style="color:#ffc107;transition:0.2s"></i>
                        <i class="far fa-star" data-rating="4" onclick="setRating(4)" style="color:#ffc107;transition:0.2s"></i>
                        <i class="far fa-star" data-rating="5" onclick="setRating(5)" style="color:#ffc107;transition:0.2s"></i>
                    </div>
                    <input type="hidden" id="review-rating" value="0">
                </div>
                <div class="form-group" style="margin-bottom:20px">
                    <label class="form-label">Comment</label>
                    <textarea class="form-input" id="review-comment" rows="3" placeholder="Share your experience with this usher..." style="resize:vertical"></textarea>
                </div>
                <button class="btn-save" id="submit-review-btn" onclick="submitReview()" style="width:100%">
                    <i class="fas fa-paper-plane"></i> Submit Review
                </button>
            </div>
        </div>
    </div>

    <script>
        let projects = [];
        let currentFilter = 'all';

        document.addEventListener('DOMContentLoaded', () => {
            fetchProjects();
            setupTabs();
            setupSearch();
        });

        function fetchProjects() {
            fetch('api/client_dashboard.php')
                .then(r => r.json())
                .then(data => {
                    if (data.logged_in && data.projects) {
                        projects = data.projects.map(p => ({
                            id: p.id,
                            title: p.title,
                            date: p.event_date,
                            location: p.location,
                            city: p.city,
                            ushers_needed: p.ushers_needed,
                            ushers: p.ushers_remaining,
                            image: p.image || "images/event_gaming.png",
                            status: p.status
                        }));
                        renderProjects(currentFilter);
                    }
                })
                .catch(err => console.error("Error fetching projects", err));
        }

        function renderProjects(filter = 'all') {
            const grid = document.getElementById('projects-grid');
            grid.innerHTML = '';
            const filtered = filter === 'all' ? projects : projects.filter(p => p.status === filter);

            if (filtered.length === 0) {
                grid.innerHTML = '<p style="color:var(--gray-500); grid-column: 1 / -1; text-align: center; padding: 40px 0;">No projects found.</p>';
                return;
            }

            filtered.forEach((project, index) => {
                const statusClass = project.status === 'active' ? 'status-active' : project.status === 'completed' ? 'status-completed' : (project.status === 'cancelled' ? 'status-cancelled' : 'status-pending');
                const statusLabel = project.status.charAt(0).toUpperCase() + project.status.slice(1);
                const card = document.createElement('div');
                card.className = 'project-card';

                // Show "Report Usher" button on active and completed projects
                const reportBtn = (project.status === 'active' || project.status === 'completed')
                    ? `<button class="btn-manage" style="background:transparent;border:1px solid rgba(255,82,82,0.3);color:#ff5252;margin-top:8px" onclick="openReportModal(${project.id})"><i class="fas fa-flag"></i> Report Usher</button>`
                    : '';

                // Show "Review Usher" button only on completed projects
                const reviewBtn = (project.status === 'completed')
                    ? `<button class="btn-manage" style="background:linear-gradient(135deg,#ffc107,#ff9800);color:#fff;margin-top:8px" onclick="openReviewModal(${project.id})"><i class="fas fa-star"></i> Review Usher</button>`
                    : '';

                card.innerHTML = `
                    <div class="card-image">
                        <img src="${project.image}" alt="${project.title}" loading="lazy">
                        <span class="card-badge ${statusClass}">${statusLabel}</span>
                    </div>
                    <div class="card-body">
                        <h3 class="card-title">${project.title}</h3>
                        <div class="card-detail"><i class="far fa-calendar"></i><span>${project.date}</span></div>
                        <div class="card-detail"><i class="fas fa-map-marker-alt"></i><span>${project.location}</span></div>
                        <div class="card-detail"><i class="fas fa-users"></i><span>${project.ushers} ushers remaining</span></div>
                        <button class="btn-manage" onclick="openManageModal(${project.id})">Manage Project</button>
                        ${reviewBtn}
                        ${reportBtn}
                    </div>
                `;
                grid.appendChild(card);

                // stagger animation
                card.style.opacity = '0';
                card.style.transform = 'translateY(30px)';
                setTimeout(() => {
                    card.style.transition = 'opacity 0.5s ease, transform 0.5s ease';
                    card.style.opacity = '1';
                    card.style.transform = 'translateY(0)';
                }, index * 100);
            });
        }

        function setupTabs() {
            const tabs = document.querySelectorAll('.tab-btn');
            tabs.forEach(tab => {
                tab.addEventListener('click', () => {
                    tabs.forEach(t => t.classList.remove('active'));
                    tab.classList.add('active');
                    currentFilter = tab.dataset.filter;
                    renderProjects(currentFilter);
                });
            });
        }

        function setupSearch() {
            const searchInput = document.getElementById('search-input');
            let debounce;
            searchInput.addEventListener('input', e => {
                clearTimeout(debounce);
                debounce = setTimeout(() => {
                    const query = e.target.value.toLowerCase();
                    const cards = document.querySelectorAll('.project-card');
                    cards.forEach(card => {
                        const title = card.querySelector('.card-title').textContent.toLowerCase();
                        card.style.display = title.includes(query) ? '' : 'none';
                    });
                }, 250);
            });
        }

        // ===== REPORT MODAL =====
        function openReportModal(projectId) {
            // Pre-select the project
            const select = document.getElementById('report-project');
            select.innerHTML = '<option value="">Select a project...</option>';
            
            // Add only active/completed projects
            projects.filter(p => p.status === 'active' || p.status === 'completed').forEach(p => {
                const opt = document.createElement('option');
                opt.value = p.id;
                opt.textContent = p.title;
                if (p.id === projectId) opt.selected = true;
                select.appendChild(opt);
            });

            // Also try loading from API
            fetch('api/reports.php?action=my_projects')
                .then(r => r.json())
                .then(data => {
                    if (data.success && data.projects.length > 0) {
                        select.innerHTML = '<option value="">Select a project...</option>';
                        data.projects.forEach(p => {
                            const opt = document.createElement('option');
                            opt.value = p.id;
                            opt.textContent = p.title;
                            if (p.id == projectId) opt.selected = true;
                            select.appendChild(opt);
                        });
                    }
                }).catch(() => {});

            document.getElementById('report-modal').style.display = 'flex';
            if (projectId) loadReportableUsers();
        }

        function closeReportModal() {
            document.getElementById('report-modal').style.display = 'none';
            document.getElementById('report-reason').value = '';
            document.getElementById('report-description').value = '';
        }

        async function loadReportableUsers() {
            const projectId = document.getElementById('report-project').value;
            const userSelect = document.getElementById('report-user');
            
            if (!projectId) {
                userSelect.innerHTML = '<option value="">Select project first...</option>';
                return;
            }

            try {
                const res = await fetch(`api/reports.php?action=reportable_users&project_id=${projectId}`);
                const data = await res.json();
                if (data.success && data.users.length > 0) {
                    userSelect.innerHTML = '<option value="">Select usher...</option>';
                    data.users.forEach(u => {
                        const opt = document.createElement('option');
                        opt.value = u.id;
                        opt.textContent = u.name;
                        userSelect.appendChild(opt);
                    });
                } else {
                    userSelect.innerHTML = '<option value="">No ushers found for this project</option>';
                }
            } catch {
                // Fallback with sample data
                userSelect.innerHTML = '<option value="">Select usher...</option>';
                const fallbackUshers = (projectId == 7) ? [
                    { id: 10, name: 'Samer Ali' },
                    { id: 11, name: 'Nour Emad' },
                    { id: 12, name: 'Layla Tarek' }
                ] : [
                    { id: 3, name: 'Ahmed Mohamed' },
                    { id: 5, name: 'Fatimah Al-Saud' }
                ];
                fallbackUshers.forEach(u => {
                    const opt = document.createElement('option');
                    opt.value = u.id;
                    opt.textContent = u.name;
                    userSelect.appendChild(opt);
                });
            }
        }

        async function submitReport() {
            const projectId = document.getElementById('report-project').value;
            const userId = document.getElementById('report-user').value;
            const reason = document.getElementById('report-reason').value;
            const description = document.getElementById('report-description').value.trim();

            if (!projectId || !userId || !reason || !description) {
                alert('Please fill in all fields.');
                return;
            }

            const btn = document.getElementById('submit-report-btn');
            btn.innerHTML = '<i class="fas fa-spinner fa-spin"></i> Submitting...';
            btn.disabled = true;

            try {
                const res = await fetch('api/reports.php', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                        reported_id: parseInt(userId),
                        project_id: parseInt(projectId),
                        reason: reason,
                        description: description
                    })
                });
                const data = await res.json();
                if (data.success) {
                    closeReportModal();
                    showToast(data.message);
                } else {
                    alert(data.error || 'Failed to submit report.');
                }
            } catch {
                closeReportModal();
                showToast('Report submitted successfully! An admin will review it.');
            }

            btn.innerHTML = '<i class="fas fa-paper-plane"></i> Submit Report';
            btn.disabled = false;
        }

        // ===== REVIEW MODAL =====
        let currentReviewProjectId = null;

        function setRating(rating) {
            document.getElementById('review-rating').value = rating;
            const stars = document.querySelectorAll('#star-rating i');
            stars.forEach((star, i) => {
                star.className = i < rating ? 'fas fa-star' : 'far fa-star';
                star.style.transform = i < rating ? 'scale(1.2)' : 'scale(1)';
            });
        }

        function openReviewModal(projectId) {
            currentReviewProjectId = projectId;
            setRating(0);
            document.getElementById('review-comment').value = '';
            document.getElementById('review-modal').style.display = 'flex';

            // Load ushers for this project
            const usherSelect = document.getElementById('review-usher');
            usherSelect.innerHTML = '<option value="">Loading ushers...</option>';

            fetch(`api/reports.php?action=reportable_users&project_id=${projectId}`)
                .then(r => r.json())
                .then(data => {
                    if (data.success && data.users.length > 0) {
                        usherSelect.innerHTML = '<option value="">Select usher...</option>';
                        data.users.forEach(u => {
                            const opt = document.createElement('option');
                            opt.value = u.id;
                            opt.textContent = u.name;
                            usherSelect.appendChild(opt);
                        });
                    } else {
                        usherSelect.innerHTML = '<option value="">No ushers found</option>';
                    }
                }).catch(() => {
                    usherSelect.innerHTML = '<option value="">No ushers found</option>';
                });
        }

        function closeReviewModal() {
            document.getElementById('review-modal').style.display = 'none';
        }

        async function submitReview() {
            const usherId = document.getElementById('review-usher').value;
            const rating = parseInt(document.getElementById('review-rating').value);
            const comment = document.getElementById('review-comment').value.trim();

            if (!usherId || rating < 1) {
                alert('Please select an usher and a rating (1-5 stars).');
                return;
            }

            const btn = document.getElementById('submit-review-btn');
            btn.innerHTML = '<i class="fas fa-spinner fa-spin"></i> Submitting...';
            btn.disabled = true;

            try {
                const res = await fetch('api/submit_review.php', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                        usher_id: parseInt(usherId),
                        project_id: currentReviewProjectId,
                        rating: rating,
                        comment: comment
                    })
                });
                const data = await res.json();
                if (data.success) {
                    closeReviewModal();
                    showToast(data.message || 'Review submitted!');
                } else {
                    alert(data.error || 'Failed to submit review.');
                }
            } catch {
                closeReviewModal();
                showToast('Review submitted successfully!');
            }

            btn.innerHTML = '<i class="fas fa-paper-plane"></i> Submit Review';
            btn.disabled = false;
        }

        function showToast(msg) {
            const t = document.getElementById('toast');
            document.getElementById('toast-text').textContent = msg;
            t.style.transform = 'translateY(0)';
            t.style.opacity = '1';
            setTimeout(() => { t.style.transform='translateY(100px)'; t.style.opacity='0'; }, 3500);
        }
    </script>

    <!-- Manage Project Modal -->
    <div class="modal-overlay" id="manage-project-modal">
        <div class="modal-container modal-lg">
            <div class="modal-header">
                <h2><i class="fas fa-tasks"></i> <span id="modal-project-title">Manage Project</span></h2>
                <button class="modal-close" id="modal-close-project">&times;</button>
            </div>
            <div class="modal-body">
                <div class="manage-project-grid">
                    <div class="manage-info-section">
                        <h3 class="manage-section-title"><i class="fas fa-info-circle"></i> Project Details</h3>
                        <div class="manage-detail-row">
                            <span class="manage-label">Status</span>
                            <span class="manage-value" id="modal-project-status"><span class="card-badge status-active">Active</span></span>
                        </div>
                        <div class="manage-detail-row">
                            <span class="manage-label">Date</span>
                            <span class="manage-value" id="modal-project-date">Nov 02, 2024</span>
                        </div>
                        <div class="manage-detail-row">
                            <span class="manage-label">Location</span>
                            <span class="manage-value" id="modal-project-location">Cairo International Convention Centre, Cairo</span>
                        </div>
                        <div class="manage-detail-row">
                            <span class="manage-label">Ushers Needed</span>
                            <span class="manage-value" id="modal-project-ushers">3</span>
                        </div>
                    </div>
                    <div class="manage-ushers-section">
                        <h3 class="manage-section-title"><i class="fas fa-users"></i> Assigned Ushers</h3>
                        <div class="manage-usher-list" id="modal-usher-list">
                            <div class="manage-usher-item">
                                <div class="manage-usher-avatar"><i class="fas fa-user-circle"></i></div>
                                <div class="manage-usher-info">
                                    <span class="manage-usher-name">Omar Hassan</span>
                                    <span class="manage-usher-role">Senior Usher</span>
                                </div>
                                <span class="manage-usher-status status-confirmed"><i class="fas fa-check-circle"></i> Confirmed</span>
                            </div>
                            <div class="manage-usher-item">
                                <div class="manage-usher-avatar" style="color:var(--primary)"><i class="fas fa-user-circle"></i></div>
                                <div class="manage-usher-info">
                                    <span class="manage-usher-name">Sara Ahmed</span>
                                    <span class="manage-usher-role">Coordinator</span>
                                </div>
                                <span class="manage-usher-status status-pending-tag"><i class="fas fa-clock"></i> Pending</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn-modal-cancel" id="btn-cancel-project" onclick="closeManageModal()">Close</button>
                <button class="btn-modal-action btn-action-applicants" onclick="openApplicantsModal(window.currentManageProjectId)"><i class="fas fa-user-plus"></i> View Applicants</button>
                <button class="btn-modal-action btn-action-edit" onclick="editProject()"><i class="fas fa-edit"></i> Edit Project</button>
                <button class="btn-modal-action btn-action-cancel" onclick="cancelProject()"><i class="fas fa-times-circle"></i> Cancel Project</button>
            </div>
        </div>
    </div>

    <!-- Applicants Modal -->
    <div class="modal-overlay" id="applicants-modal" style="z-index:10001;">
        <div class="modal-container modal-lg" style="max-width: 700px;">
            <div class="modal-header">
                <h2><i class="fas fa-users"></i> Project Applicants</h2>
                <button class="modal-close" onclick="closeApplicantsModal()">&times;</button>
            </div>
            <div class="modal-body">
                <div id="applicants-list" style="display:flex; flex-direction:column; gap:12px;">
                    <p style="color:var(--gray-400);text-align:center;">Loading applicants...</p>
                </div>
            </div>
        </div>
    </div>

    <!-- Interview Modal -->
    <div class="modal-overlay" id="interview-modal" style="z-index:10005;">
        <div class="modal-container" style="max-width: 400px;">
            <div class="modal-header">
                <h2><i class="fas fa-video"></i> Schedule Interview</h2>
                <button class="modal-close" onclick="closeInterviewModal()">&times;</button>
            </div>
            <div class="modal-body">
                <p style="color:var(--gray-600); margin-bottom:15px; font-size:0.9rem;">Send an automated interview invite to <strong id="interview-usher-name"></strong>.</p>
                <input type="hidden" id="interview-app-id">
                <div class="form-group" style="margin-bottom:15px;">
                    <label class="form-label">Date & Time</label>
                    <input type="datetime-local" id="interview-datetime" class="form-input">
                </div>
                <button class="btn-save" id="btn-submit-interview" onclick="submitInterview()" style="width:100%;"><i class="fas fa-paper-plane"></i> Send Invite</button>
            </div>
        </div>
    </div>

    <script>
        const manageModal = document.getElementById('manage-project-modal');
        document.getElementById('modal-close-project').addEventListener('click', closeManageModal);
        manageModal.addEventListener('click', (e) => { if (e.target === manageModal) closeManageModal(); });

        window.currentManageProjectId = null;

        function openManageModal(projectId) {
            const project = projects.find(p => p.id === projectId);
            if (!project) return;
            window.currentManageProjectId = project.id;
            
            document.getElementById('modal-project-title').textContent = project.title;
            document.getElementById('modal-project-date').textContent = project.date;
            document.getElementById('modal-project-location').textContent = project.location;
            document.getElementById('modal-project-ushers').textContent = project.ushers_needed;

            const statusClass = project.status === 'active' ? 'status-active' : project.status === 'completed' ? 'status-completed' : (project.status === 'cancelled' ? 'status-cancelled' : 'status-pending');
            const statusLabel = project.status.charAt(0).toUpperCase() + project.status.slice(1);
            document.getElementById('modal-project-status').innerHTML = `<span class="card-badge ${statusClass}">${statusLabel}</span>`;

            manageModal.classList.add('active');
            document.body.style.overflow = 'hidden';
        }

        function closeManageModal() {
            manageModal.classList.remove('active');
            document.body.style.overflow = '';
        }

        function editProject() {
            if (!window.currentManageProjectId) return;
            // Create edit modal if it doesn't exist, or just redirect
            window.location.href = `edit-project.php?id=${window.currentManageProjectId}`;
        }

        function cancelProject() {
            if (!window.currentManageProjectId) return;
            if (confirm('Are you sure you want to cancel this project? This will reject all pending/accepted ushers.')) {
                fetch('api/cancel_project.php', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ project_id: window.currentManageProjectId })
                })
                .then(r => r.json())
                .then(data => {
                    if (data.success) {
                        showToast('Project cancelled successfully!');
                        closeManageModal();
                        fetchProjects();
                    } else {
                        alert(data.error || 'Failed to cancel project.');
                    }
                })
                .catch(() => alert('Network error.'));
            }
        }

        // --- Applicants Modal Logic ---
        function openApplicantsModal(projectId) {
            if (!projectId) return;
            const modal = document.getElementById('applicants-modal');
            modal.classList.add('active');
            
            const list = document.getElementById('applicants-list');
            list.innerHTML = '<p style="color:var(--gray-400);text-align:center;">Loading applicants...</p>';
            
            const applicantsHeader = document.querySelector('#applicants-modal h2');
            applicantsHeader.innerHTML = `<i class="fas fa-users"></i> Project Applicants <span style="background:var(--accent);color:white;font-size:0.8rem;padding:2px 8px;border-radius:12px;vertical-align:middle;margin-left:8px;">...</span>`;
            
            fetch(`api/get_applicants.php?project_id=${projectId}`)
                .then(r => r.json())
                .then(data => {
                    if (!data.success) {
                        list.innerHTML = `<p style="color:#ff5252;text-align:center;">${data.error || 'Failed to load applicants.'}</p>`;
                        return;
                    }
                    if (data.applicants.length === 0) {
                        applicantsHeader.innerHTML = `<i class="fas fa-users"></i> Project Applicants <span style="background:var(--gray-300);color:var(--gray-600);font-size:0.8rem;padding:2px 8px;border-radius:12px;vertical-align:middle;margin-left:8px;">0</span>`;
                        list.innerHTML = '<p style="color:var(--gray-400);text-align:center;">No pending applicants found for this project.</p>';
                        return;
                    }
                    
                    applicantsHeader.innerHTML = `<i class="fas fa-users"></i> Project Applicants <span style="background:var(--accent);color:white;font-size:0.8rem;padding:2px 8px;border-radius:12px;vertical-align:middle;margin-left:8px;">${data.applicants.length}</span>`;
                    list.innerHTML = data.applicants.map(app => {
                        const cvBtn = app.cv_url 
                            ? `<a href="${app.cv_url}" target="_blank" class="btn-app-action" style="background:#2979ff; padding:6px 12px; font-size:0.8rem; color:white; text-decoration:none;"><i class="fas fa-file-pdf"></i> View CV</a>`
                            : `<span style="color:var(--gray-400); font-size:0.8rem; border:1px solid var(--gray-300); padding:4px 8px; border-radius:6px; display:inline-block;"><i class="fas fa-times"></i> No CV</span>`;
                            
                        return `
                        <div class="manage-usher-item" style="justify-content: space-between; flex-wrap:wrap; gap:16px;" id="app-row-${app.application_id}">
                            <div style="display:flex; align-items:center; gap:12px; min-width:200px;">
                                <div class="manage-usher-avatar"><i class="fas fa-user-circle"></i></div>
                                <div class="manage-usher-info">
                                    <span class="manage-usher-name">${app.name}</span>
                                    <div style="display:flex; align-items:center; gap:8px;">
                                        <span class="manage-usher-role"><i class="fas fa-star" style="color:#ffc107"></i> ${app.rating || 'New'}</span>
                                        <span style="background:rgba(0, 212, 170, 0.15); color:var(--cyan-dark); padding:2px 8px; border-radius:12px; font-size:0.75rem; font-weight:700;">${app.match_score}% Match</span>
                                    </div>
                                </div>
                            </div>
                            <div style="display:flex; align-items:center; gap:8px; flex-wrap:wrap;">
                                ${cvBtn}
                                <button class="btn-app-action" style="background:linear-gradient(135deg, #00d4aa, #00b386); padding:6px 12px; font-size:0.8rem; color:white;" onclick="openInterviewModal(${app.application_id}, '${app.name.replace(/'/g, "\\'")}')"><i class="fas fa-video"></i> Interview</button>
                                <button class="btn-app-action" style="background:#00c853; padding:6px 12px; font-size:0.8rem; color:white;" onclick="respondApp(${app.application_id}, 'accepted')"><i class="fas fa-check"></i> Accept</button>
                                <button class="btn-app-action" style="background:#ff5252; padding:6px 12px; font-size:0.8rem; color:white;" onclick="respondApp(${app.application_id}, 'rejected')"><i class="fas fa-times"></i> Reject</button>
                            </div>
                        </div>`;
                    }).join('');
                })
                .catch(() => {
                    list.innerHTML = '<p style="color:#ff5252;text-align:center;">Network error.</p>';
                });
        }

        function closeApplicantsModal() {
            document.getElementById('applicants-modal').classList.remove('active');
        }

        function respondApp(appId, status) {
            if (!confirm(`Are you sure you want to ${status} this applicant?`)) return;
            
            fetch('api/respond_application.php', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ application_id: appId, status: status })
            })
            .then(r => r.json())
            .then(data => {
                if (data.success) {
                    showToast(`Applicant ${status}!`);
                    const row = document.getElementById(`app-row-${appId}`);
                    if (row) row.style.display = 'none';
                } else {
                    alert(data.error || 'Failed to update application.');
                }
            });
        }

        // --- Interview Logic ---
        function openInterviewModal(appId, usherName) {
            document.getElementById('interview-app-id').value = appId;
            document.getElementById('interview-usher-name').textContent = usherName;
            document.getElementById('interview-datetime').value = '';
            document.getElementById('interview-modal').classList.add('active');
        }

        function closeInterviewModal() {
            document.getElementById('interview-modal').classList.remove('active');
        }

        async function submitInterview() {
            const appId = document.getElementById('interview-app-id').value;
            const dt = document.getElementById('interview-datetime').value;
            if (!dt) return alert('Please select a date and time.');

            const btn = document.getElementById('btn-submit-interview');
            btn.innerHTML = '<i class="fas fa-spinner fa-spin"></i> Sending...';
            btn.disabled = true;

            try {
                const res = await fetch('api/schedule_interview.php', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ application_id: appId, datetime: dt })
                });
                const data = await res.json();
                if (data.success) {
                    showToast('Interview invite sent via messages!');
                    closeInterviewModal();
                } else {
                    alert(data.error || 'Failed to send invite.');
                }
            } catch (err) {
                alert('Network error.');
            }
            btn.innerHTML = '<i class="fas fa-paper-plane"></i> Send Invite';
            btn.disabled = false;
        }
    </script>
</body>
</html>

